repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: 9c72c5f9f05200fdc06e3f1b16e9aaa89fbe9f75  # v8.24.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
