font_family     JetBrainsMono Nerd Font Mono
font_size       14

cursor_shape                block
cursor_beam_thickness       1.5
cursor_underline_thickness  2.0
cursor_blink_interval       0.5
cursor_stop_blinking_after  0

tab_bar_style               powerline
tab_bar_min_tabs            2

window_margin_width         2
active_border_color         #89b4fa
inactive_border_color       #313244

remember_window_size        no
initial_window_width        900
initial_window_height       500

background_opacity          0.75
dynamic_background_opacity  yes
background_blur             0
window_padding_width        10

shell                       zsh
shell_integration           enabled

enable_audio_bell           no

sync_to_monitor             yes

confirm_os_window_close     0

notify_on_cmd_finish        unfocused 30.0
notification_system_bell    yes


map kitty_mod+enter         new_window_with_cwd
map kitty_mod+n             new_os_window_with_cwd
map kitty_mod+t             new_tab_with_cwd

map alt+1                  goto_tab 1
map alt+2                  goto_tab 2
map alt+3                  goto_tab 3
map alt+4                  goto_tab 4
map alt+5                  goto_tab 5
map alt+6                  goto_tab 6
map alt+7                  goto_tab 7
map alt+8                  goto_tab 8
map alt+9                  goto_tab 9
map alt+0                  goto_tab 0

map kitty_mod+alt+t         set_tab_title

map kitty_mod+0             change_font_size all 0

map kitty_mod+o>1           set_background_opacity 1.0
map kitty_mod+o>9           set_background_opacity 0.8
map kitty_mod+o>8           set_background_opacity 0.6
map kitty_mod+o>7           set_background_opacity 0.4
map kitty_mod+o>6           set_background_opacity 0.2
map kitty_mod+o>0           set_background_opacity default

allow_remote_control yes

# BEGIN_KITTY_THEME
# Matugen
include colors.conf
# END_KITTY_THEME
