[config.wallpaper]
set = true

command = "swww"
# arguments = ["img", "--transition-type", "center"]
arguments = ["img"]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload  >/dev/null 2>&1 &'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'bash ~/.config/kitty/reload.sh'

[templates.wofi]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'bash ~/.config/waybar/reload.sh'

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'
