ipc = true
preload = ~/Pictures/Wallpapers/wallpaper-1.jpg
preload = ~/Pictures/Wallpapers/wallpaper-2.jpg
preload = ~/Pictures/Wallpapers/wallpaper-3.jpg
preload = ~/Pictures/Wallpapers/wallpaper-4.jpg
preload = ~/Pictures/Wallpapers/wallpaper-5.jpg
preload = ~/Pictures/Wallpapers/wallpaper-6.jpg
preload = ~/Pictures/Wallpapers/wallpaper-7.jpg
# wallpaper = ,/home/shush/Pictures/Wallpapers/wallpaper-7.jpg
