general {
    lock_cmd = pidof hyprlock |

| hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# 1. Dim the screen after 2.5 minutes
listener {
    timeout = 150                                # 2.5min
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum
    on-resume = brightnessctl -r                 # monitor backlight restore
}

# 2. Lock the screen after 5 minutes
listener {
    timeout = 300                                # 5min
    on-timeout = loginctl lock-session           # lock screen
}

# 3. Turn off the screen 30 seconds after locking
listener {
    timeout = 330                                # 5.5min
    on-timeout = hyprctl dispatch dpms off       # screen off
    on-resume = hyprctl dispatch dpms on         # screen on when activity is detected
}

# 4. Suspend the PC after 15 minutes
listener {
    timeout = 900                                # 15min
    on-timeout = systemctl suspend               # suspend pc
}
