#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    # kb_options = grp:ralt_rshift_toggle 
    kb_rules =

    follow_mouse = 1

    # sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    # accel_profile = flat
    # force_no_accel = true

    # touchpad {
    #     natural_scroll = true
    # }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = elan0001:00-04f3:3140-touchpad
    sensitivity = 0.75
    accel_profile = flat
    natural_scroll = true
    scroll_factor = 0.25
}

device {
    name = steelseries-steelseries-rival-3
    sensitivity = 0
    accel_profile = flat
}

